### PR TITLE
Upgrade to Db v2.13

### PR DESCRIPTION
**Pull request by franck-boullier**
Upgrade the BZ database to v2.13

### CODE REVIEW

**Comment by franck-boullier** [comment]
This has been tested in my local environment (AWS) and works as intended

**Comment by kaihendry** [comment]
How do I test this works?

Or should I just merge?

**Comment by franck-boullier** [comment]
@kaihendry you can test on your local envo (it should deploy without hitches) and then merge

**Comment by kaihendry** [comment]
Appears to work, as in I can login as Administrator.

https://s.natalian.org/2018-01-15/1516019961_2558x1406.png

But AFAICT there are no other users https://github.com/unee-t/bugzilla-customisation#login-info-set-by-sqldemosqlgz and there is no API keys setup.

**Comment by franck-boullier** [comment]
@Kaihendry
But AFAICT there are no other users https://github.com/unee-t/bugzilla-customisation#login-info-set-by-sqldemosqlgz and there is no API keys setup.

This is correct: these need to be added later with the "insert demo users script"

The API key is also environment specific so not set there in the demo.sql script either

**Pull request merged**
