### PR TITLE
Update terminology

### PR DESCRIPTION
**Pull request by franck-boullier**
Replace 'Bugzilla' with Unee-T in different places.

### CODE REVIEW

**Comment by kaihendry** [comment]
Could see no evidence of "Replace 'Bugzilla' with Unee-T in different places.". 

Ideally you need to describe how to test what this new pull request does otherwise I have no idea how to verify you're doing what you set out to do.

Might a sed replacing Bugzilla with Unee-T be a better approach instead of committing new templates? Just a suggestion.

**Comment by franck-boullier** [comment]
In the code I posted, each time the hard coded word 'bugzilla appears it is replaced with a variable instead.

To test go to the page where the code is used (ex in the Reports page) and verify that the term 'bugzilla' is correctly replaced

**Comment by franck-boullier** [comment]
Since this is done by customizing the template you have to
1- identify the original file in the default template
2- copy this file in the custom folder
3- alter the file in the custom folder

This is why GH sees this as a new addition: file did not exist in the custom folder before because we used the default version

**Comment by franck-boullier** [comment]
"Might a sed replacing Bugzilla with Unee-T be a better approach instead of committing new templates?"
Impossible unfortunately as 'bugzilla' is also a word used in variable names and code that we don't want to touch because it'll break basically everything.

**Comment by kaihendry** [comment]
Ideally I need a URL and screen shot to make this easier to verify. I am going to assume you've tested it. Seems like a trivial change besides.

**Comment by franck-boullier** [comment]
Ok noted 
Will do a better job next time ;-)
Thanks!

**Pull request merged**
