### PR TITLE
Differentiate environments

### PR DESCRIPTION
**Pull request by franck-boullier**
Create different color codes to be able to differentiate each environments when appropriate.

### CODE REVIEW

**Comment by franck-boullier** [comment]
@kaihendry can we merge this before we redeploy the dev and prod.

**Comment by kaihendry** [comment]
You need to have the different skins/templates referenced in https://github.com/unee-t/bugzilla-customisation/blob/master/Dockerfile#L18 since we don't do Volume mounts when we deploy to AWS

**Comment by franck-boullier** [comment]
Let's put this on hold for now
I might have a more efficient way to do this using the extension mechanism more efficiently...

**Comment by franck-boullier** [comment]
closing this as we might have a more efficient solution...

**Pull request closed without merging**
