### PR TITLE
include demo users and demo units

### PR DESCRIPTION
**Pull request by franck-boullier**
This is to fix issue #56

### CODE REVIEW

**Comment by franck-boullier** [comment]
@kaihendry can you test this: the DB primer should now include the demo users and units as described here:
https://documentation.unee-t.com/2018/03/01/introduction-to-the-demo-environment/

**Comment by kaihendry** [comment]
I think it works: https://s.natalian.org/2018-04-10/setup-demo.mp4

```
[hendry@t480s ~]$ curl http://localhost:3000/api/pending-invitations?accessToken=blablabla
[
  {
    "_id": "43uPg9vWALuv7tziC",
    "invitedBy": 7,
    "invitee": 19,
    "role": "Tenant",
    "isOccupant": true,
    "caseId": 1,
    "unitId": 2,
    "type": "type_assigned"
  }
]
```

So hopefully I can go from https://github.com/unee-t/bugzilla-customisation/wiki/Process-Invitations-in-the-BZ-database and fix https://github.com/unee-t/bugzilla-customisation/issues/46 ...

**Comment by franck-boullier** [comment]
Please note that this does NOT setup the MEFE users, only the BZFE users

We still need to create the MEFE user (signup) and associated these to their corresponding BZFE user.
The MEFE users are managed in the MongoDB

**Comment by kaihendry** [comment]
Yup, as you can see from the screencast https://s.natalian.org/2018-04-10/setup-demo.mp4 ... I register leonel@example.com. Then I proceed to invite a new user. I did good, right?

**Review by kaihendry — APPROVED** [review]

**Pull request merged**
